/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedBookRouteImport } from './routes/embed.book'
import { Route as EmbedAvailabilityRouteImport } from './routes/embed.availability'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicBookingConfigRouteImport } from './routes/api/public/booking/config'
import { Route as ApiPublicBookingBookRouteImport } from './routes/api/public/booking/book'
import { Route as ApiPublicBookingAvailabilityRouteImport } from './routes/api/public/booking/availability'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedBookRoute = EmbedBookRouteImport.update({
  id: '/embed/book',
  path: '/embed/book',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAvailabilityRoute = EmbedAvailabilityRouteImport.update({
  id: '/embed/availability',
  path: '/embed/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingConfigRoute = ApiPublicBookingConfigRouteImport.update({
  id: '/api/public/booking/config',
  path: '/api/public/booking/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingBookRoute = ApiPublicBookingBookRouteImport.update({
  id: '/api/public/booking/book',
  path: '/api/public/booking/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingAvailabilityRoute =
  ApiPublicBookingAvailabilityRouteImport.update({
    id: '/api/public/booking/availability',
    path: '/api/public/booking/availability',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clientes': typeof ClientesRoute
  '/estadisticas': typeof EstadisticasRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/embed/availability': typeof EmbedAvailabilityRoute
  '/embed/book': typeof EmbedBookRoute
  '/api/public/booking/availability': typeof ApiPublicBookingAvailabilityRoute
  '/api/public/booking/book': typeof ApiPublicBookingBookRoute
  '/api/public/booking/config': typeof ApiPublicBookingConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clientes': typeof ClientesRoute
  '/estadisticas': typeof EstadisticasRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/embed/availability': typeof EmbedAvailabilityRoute
  '/embed/book': typeof EmbedBookRoute
  '/api/public/booking/availability': typeof ApiPublicBookingAvailabilityRoute
  '/api/public/booking/book': typeof ApiPublicBookingBookRoute
  '/api/public/booking/config': typeof ApiPublicBookingConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/clientes': typeof ClientesRoute
  '/estadisticas': typeof EstadisticasRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/embed/availability': typeof EmbedAvailabilityRoute
  '/embed/book': typeof EmbedBookRoute
  '/api/public/booking/availability': typeof ApiPublicBookingAvailabilityRoute
  '/api/public/booking/book': typeof ApiPublicBookingBookRoute
  '/api/public/booking/config': typeof ApiPublicBookingConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/clientes'
    | '/estadisticas'
    | '/holidays'
    | '/login'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/auth/callback'
    | '/embed/availability'
    | '/embed/book'
    | '/api/public/booking/availability'
    | '/api/public/booking/book'
    | '/api/public/booking/config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/clientes'
    | '/estadisticas'
    | '/holidays'
    | '/login'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/auth/callback'
    | '/embed/availability'
    | '/embed/book'
    | '/api/public/booking/availability'
    | '/api/public/booking/book'
    | '/api/public/booking/config'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/clientes'
    | '/estadisticas'
    | '/holidays'
    | '/login'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/auth/callback'
    | '/embed/availability'
    | '/embed/book'
    | '/api/public/booking/availability'
    | '/api/public/booking/book'
    | '/api/public/booking/config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ClientesRoute: typeof ClientesRoute
  EstadisticasRoute: typeof EstadisticasRoute
  HolidaysRoute: typeof HolidaysRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmbedAvailabilityRoute: typeof EmbedAvailabilityRoute
  EmbedBookRoute: typeof EmbedBookRoute
  ApiPublicBookingAvailabilityRoute: typeof ApiPublicBookingAvailabilityRoute
  ApiPublicBookingBookRoute: typeof ApiPublicBookingBookRoute
  ApiPublicBookingConfigRoute: typeof ApiPublicBookingConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/book': {
      id: '/embed/book'
      path: '/embed/book'
      fullPath: '/embed/book'
      preLoaderRoute: typeof EmbedBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/availability': {
      id: '/embed/availability'
      path: '/embed/availability'
      fullPath: '/embed/availability'
      preLoaderRoute: typeof EmbedAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/config': {
      id: '/api/public/booking/config'
      path: '/api/public/booking/config'
      fullPath: '/api/public/booking/config'
      preLoaderRoute: typeof ApiPublicBookingConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/book': {
      id: '/api/public/booking/book'
      path: '/api/public/booking/book'
      fullPath: '/api/public/booking/book'
      preLoaderRoute: typeof ApiPublicBookingBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/availability': {
      id: '/api/public/booking/availability'
      path: '/api/public/booking/availability'
      fullPath: '/api/public/booking/availability'
      preLoaderRoute: typeof ApiPublicBookingAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ClientesRoute: ClientesRoute,
  EstadisticasRoute: EstadisticasRoute,
  HolidaysRoute: HolidaysRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmbedAvailabilityRoute: EmbedAvailabilityRoute,
  EmbedBookRoute: EmbedBookRoute,
  ApiPublicBookingAvailabilityRoute: ApiPublicBookingAvailabilityRoute,
  ApiPublicBookingBookRoute: ApiPublicBookingBookRoute,
  ApiPublicBookingConfigRoute: ApiPublicBookingConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
