/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AiConfigRouteImport } from './routes/ai-config'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAiToolsRescheduleRouteImport } from './routes/api/public/ai-tools/reschedule'
import { Route as ApiPublicAiToolsCancelRouteImport } from './routes/api/public/ai-tools/cancel'
import { Route as ApiPublicAiToolsBookRouteImport } from './routes/api/public/ai-tools/book'
import { Route as ApiPublicAiToolsAvailabilityRouteImport } from './routes/api/public/ai-tools/availability'
import { Route as ApiPublicAdminApiKeysRouteImport } from './routes/api/public/admin/api-keys'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConfigRoute = AiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiToolsRescheduleRoute =
  ApiPublicAiToolsRescheduleRouteImport.update({
    id: '/api/public/ai-tools/reschedule',
    path: '/api/public/ai-tools/reschedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiToolsCancelRoute = ApiPublicAiToolsCancelRouteImport.update({
  id: '/api/public/ai-tools/cancel',
  path: '/api/public/ai-tools/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiToolsBookRoute = ApiPublicAiToolsBookRouteImport.update({
  id: '/api/public/ai-tools/book',
  path: '/api/public/ai-tools/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiToolsAvailabilityRoute =
  ApiPublicAiToolsAvailabilityRouteImport.update({
    id: '/api/public/ai-tools/availability',
    path: '/api/public/ai-tools/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminApiKeysRoute = ApiPublicAdminApiKeysRouteImport.update({
  id: '/api/public/admin/api-keys',
  path: '/api/public/admin/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-config': typeof AiConfigRoute
  '/calendar': typeof CalendarRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/api/public/admin/api-keys': typeof ApiPublicAdminApiKeysRoute
  '/api/public/ai-tools/availability': typeof ApiPublicAiToolsAvailabilityRoute
  '/api/public/ai-tools/book': typeof ApiPublicAiToolsBookRoute
  '/api/public/ai-tools/cancel': typeof ApiPublicAiToolsCancelRoute
  '/api/public/ai-tools/reschedule': typeof ApiPublicAiToolsRescheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-config': typeof AiConfigRoute
  '/calendar': typeof CalendarRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/api/public/admin/api-keys': typeof ApiPublicAdminApiKeysRoute
  '/api/public/ai-tools/availability': typeof ApiPublicAiToolsAvailabilityRoute
  '/api/public/ai-tools/book': typeof ApiPublicAiToolsBookRoute
  '/api/public/ai-tools/cancel': typeof ApiPublicAiToolsCancelRoute
  '/api/public/ai-tools/reschedule': typeof ApiPublicAiToolsRescheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-config': typeof AiConfigRoute
  '/calendar': typeof CalendarRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/api/public/admin/api-keys': typeof ApiPublicAdminApiKeysRoute
  '/api/public/ai-tools/availability': typeof ApiPublicAiToolsAvailabilityRoute
  '/api/public/ai-tools/book': typeof ApiPublicAiToolsBookRoute
  '/api/public/ai-tools/cancel': typeof ApiPublicAiToolsCancelRoute
  '/api/public/ai-tools/reschedule': typeof ApiPublicAiToolsRescheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-config'
    | '/calendar'
    | '/holidays'
    | '/login'
    | '/services'
    | '/team'
    | '/api/public/admin/api-keys'
    | '/api/public/ai-tools/availability'
    | '/api/public/ai-tools/book'
    | '/api/public/ai-tools/cancel'
    | '/api/public/ai-tools/reschedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-config'
    | '/calendar'
    | '/holidays'
    | '/login'
    | '/services'
    | '/team'
    | '/api/public/admin/api-keys'
    | '/api/public/ai-tools/availability'
    | '/api/public/ai-tools/book'
    | '/api/public/ai-tools/cancel'
    | '/api/public/ai-tools/reschedule'
  id:
    | '__root__'
    | '/'
    | '/ai-config'
    | '/calendar'
    | '/holidays'
    | '/login'
    | '/services'
    | '/team'
    | '/api/public/admin/api-keys'
    | '/api/public/ai-tools/availability'
    | '/api/public/ai-tools/book'
    | '/api/public/ai-tools/cancel'
    | '/api/public/ai-tools/reschedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiConfigRoute: typeof AiConfigRoute
  CalendarRoute: typeof CalendarRoute
  HolidaysRoute: typeof HolidaysRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  ApiPublicAdminApiKeysRoute: typeof ApiPublicAdminApiKeysRoute
  ApiPublicAiToolsAvailabilityRoute: typeof ApiPublicAiToolsAvailabilityRoute
  ApiPublicAiToolsBookRoute: typeof ApiPublicAiToolsBookRoute
  ApiPublicAiToolsCancelRoute: typeof ApiPublicAiToolsCancelRoute
  ApiPublicAiToolsRescheduleRoute: typeof ApiPublicAiToolsRescheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-config': {
      id: '/ai-config'
      path: '/ai-config'
      fullPath: '/ai-config'
      preLoaderRoute: typeof AiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-tools/reschedule': {
      id: '/api/public/ai-tools/reschedule'
      path: '/api/public/ai-tools/reschedule'
      fullPath: '/api/public/ai-tools/reschedule'
      preLoaderRoute: typeof ApiPublicAiToolsRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-tools/cancel': {
      id: '/api/public/ai-tools/cancel'
      path: '/api/public/ai-tools/cancel'
      fullPath: '/api/public/ai-tools/cancel'
      preLoaderRoute: typeof ApiPublicAiToolsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-tools/book': {
      id: '/api/public/ai-tools/book'
      path: '/api/public/ai-tools/book'
      fullPath: '/api/public/ai-tools/book'
      preLoaderRoute: typeof ApiPublicAiToolsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-tools/availability': {
      id: '/api/public/ai-tools/availability'
      path: '/api/public/ai-tools/availability'
      fullPath: '/api/public/ai-tools/availability'
      preLoaderRoute: typeof ApiPublicAiToolsAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/api-keys': {
      id: '/api/public/admin/api-keys'
      path: '/api/public/admin/api-keys'
      fullPath: '/api/public/admin/api-keys'
      preLoaderRoute: typeof ApiPublicAdminApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiConfigRoute: AiConfigRoute,
  CalendarRoute: CalendarRoute,
  HolidaysRoute: HolidaysRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  ApiPublicAdminApiKeysRoute: ApiPublicAdminApiKeysRoute,
  ApiPublicAiToolsAvailabilityRoute: ApiPublicAiToolsAvailabilityRoute,
  ApiPublicAiToolsBookRoute: ApiPublicAiToolsBookRoute,
  ApiPublicAiToolsCancelRoute: ApiPublicAiToolsCancelRoute,
  ApiPublicAiToolsRescheduleRoute: ApiPublicAiToolsRescheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
